### PR TITLE
responsive-design, 

### PR DESCRIPTION
**Pull request by kotoku-code**
## Clone of Next-Web homepage.
- Added media queries for phone and tablet break-points
- use of CSS grid to make it responsive
- All stickler issues cleared

[Live Version](https://friendly-babbage-bb5770.netlify.com/)

If you have any further questions for us to clarify, please ask.

kind regards

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @kotoku-code & @Krishnabot  Nice try on this project:clap:. Let's now take care of the following:**

1. The appearance of all elements (nav, main, footer) on small screens does not look like the original. Please look into this.

2. The page has a sub-navigation bar. Yours is missing.
image

3. The logo should appear at the top-left corner on medium screens.

4. On large screens, the TNW logo should be positioned at the top-left corner of the top-three news section. Compare yours with the original.

5. You should target the following break point. Small screens - less than 700px, medium screen - greater than 700px & less than 1000px and large screens - above 1000px

6. Remove all commented code in stylesheet and anywhere else you find them.

7. Group all css files in a folder to keep the project folder neat.

8. Links in the section below are not properly displayed.
image

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by kotoku-code** [comment]
1. fixed mobile phone media query
2.when we started the project next-web did not have this sub-navigation bar but introduced it afew days later.
3. corrected logo placement
4. logo appears in top right corner of main images
5. we chose the break-points based off i-phonex and ipad break-points.
6.comments removed
7. css files now placed inside a css folder
8.readme file corrected

**Comment by uryelah** [comment]
Hello **Krishna Acharya** & **Kotoku Kennedy**, I'm Sarah, your reviewer for this PR 👩‍🚀 

You did a good job completing the changes from the last review, congrats! 

**Great job at:** 🥇
- great use of gradients
- styling 'Latest founding rounds' really well
- making a great footer
- adding CSS hover effects

**You still need to work on some changes before you can move on to the next project though**
-----

### Required changes 🛠 
### 

- [ ] **Please fix your Stickler checks**

- [x] The navigation bar changing to a hamburger menu happens before, at a wider screen, in the original page compared with your clone. Please check the [original page](https://thenextweb.com/) breaking points with your [browser developer tools](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) and adjust them.

- [x] Please fix the positioning of the secondary navbar, it has some space between it and the one above in big screens, and the color of the link

Screenshot_2020-03-02 Responsive Design(5)

- [x] Please fix the text overflow issues found in your clone in big screens, examples bellow:
Screenshot_2020-03-02 Responsive Design(2)

Screenshot_2020-03-02 Responsive Design(3)

Screenshot_2020-03-02 Responsive Design(4)

- [x] For the first 3 images all images take the maximum width and are aligned in one column and don't take more than 100% of the device width. **Please fix the horizontal scroll on small screens.**

- [x] The latest news, funding rounds section and following sections are not centrally aligned on medium and small screens. Please fix the extra space at the left of the screen.
Screenshot_2020-03-02 Responsive Design(6)

- [x] The footer does not change through the breakpoints. Please check the [original page](https://thenextweb.com/)  and compare it with your footer bellow.
Screenshot_2020-03-02 Responsive Design(7)

- [x] Make sure your clone breakpoints are breaking at similar screen sizes than the original page.

-------

**Kindly please fix the required changes 👷  before asking for a new code review**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — COMMENTED** [review]
# This is an amazing job @kotoku-code and @Krishnabot :medal_military: 
You have done a great job building this! Please consider my comment below, make the appropriate change and request another review! I wish you the very best and see you at the top :100: 

#### Overflowing content
Please note that the content of your page is overflowing into the navigation bar as you scroll down the page, it seems like you have a z-index problem. Please look into this, make the necessary changes and request another review. I wish you all the best :handshake: 
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by kotoku-code** [comment]
hi tolulope,

we cannot see your comments also in the pull request on github we cannot
see your comments.

please update us when your ready.

kind regards

**Comment by kotoku-code** [comment]
fixed z-index on nav

**Review by nikasulo — APPROVED** [review]
# Great work! @kotoku-code and @Krishnabot :medal_military: 
Your skills are interesting and impressive, I commend you both :handshake: Please merge and keep moving forward with the same energy :smile: I wish you the very best and see you on top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
